defaults:
    - _self_
    - general : general_default
    - dataset : planar
    - model   : digress
    - train   : train_default
    - digress_experiment: ???

hydra:
  job:
    chdir: True
  run:
    dir: runs/digress/${dataset.name}/marginal/layers=${model.n_layers}
