defaults:
    - _self_
    - general : general_default
    - dataset : planar
    - model   : construct
    - train   : train_default
    - optional construct_tagg_experiment: ???

hydra:
  job:
    chdir: True
  run:
    dir: runs/construct_tagg/${dataset.name}/${model.transition}/rev_proj=${model.rev_proj}/layers=${model.n_layers}
